### ISSUE TITLE
Create a test mode for both RPC Servers and Clients

### ISSUE THREAD

**Issue by shamil614** [C-S-D/carrot_rpc#33]
A test mode is a means to provide better infrastructure for testing. When carrot is passed a command line flag `--server_test_mode` the server queue names would be modified to such that "_test" is appended to the end of the names. Also when used in conjunction `--autoload_rails` the `RAILS_ENV` `RACK_ENV` is set to "test". 

The client would operate similarly except that there would be a configuration option like `config.client_test_mode`. Much like the server, the client queue name would have `_test` appended.

All this combined allows for messages to be sent to a different set of queues and a different ruby process when testing. And any database queries use the test database and not the development database.

**Comment by thewalkingtoast** [comment]
Fixed by #34
